<script setup lang="ts">
import Text from "~/gla_ui/components/atom/Text.vue";
import Flex from "~/gla_ui/components/atom/Flex.vue";
</script>

<template>
<Flex
  :gap="[12]"
>
  <Flex
    direction="column"
    :gap="[4]"
  >
    <Text
      family="heading"
      size="default"
    >
      Heading_default
    </Text>
    <Text
      family="heading"
      size="xs"
    >
      Heading_xs
    </Text>
    <Text
      family="heading"
      size="sm"
    >
      Heading_sm
    </Text>
    <Text
      family="heading"
      size="md"
    >
      Heading_md
    </Text>
    <Text
      family="heading"
      size="lg"
    >
      Heading_lg
    </Text>
    <Text
      family="heading"
      size="xl"
    >
      Heading_xl
    </Text>
  </Flex>
  <Flex
    direction="column"
    :gap="[4]"
  >
    <Text
      family="body"
      size="default"
    >
      Body_default
    </Text>
    <Text
      family="body"
      size="xs"
    >
      Body_xs
    </Text>
    <Text
      family="body"
      size="sm"
    >
      Body_sm
    </Text>
    <Text
      family="body"
      size="md"
    >
      Body_md
    </Text>
    <Text
      family="body"
      size="lg"
    >
      Body_lg
    </Text>
    <Text
      family="body"
      size="xl"
    >
      Body_xl
    </Text>
  </Flex>
  <Flex
    direction="column"
    :gap="[4]"
  >
    <Text
      family="body"
      size="default"
      class="mono"
    >
      Mono_default
    </Text>
    <Text
      family="body"
      size="xs"
      class="mono"
    >
      Mono_xs
    </Text>
    <Text
      family="body"
      size="sm"
      class="mono"
    >
      Mono_sm
    </Text>
    <Text
      family="body"
      size="md"
      class="mono"
    >
      Mono_md
    </Text>
    <Text
      family="body"
      size="lg"
      class="mono"
    >
      Mono_lg
    </Text>
    <Text
      family="body"
      size="xl"
      class="mono"
    >
      Mono_xl
    </Text>
  </Flex>
  <Flex
    direction="column"
    :gap="[4]"
  >
    <Text
      family="heading"
      size="default"
      class="mono"
    >
      MonoBIG_default
    </Text>
    <Text
      family="heading"
      size="xs"
      class="mono"
    >
      MonoBIG_xs
    </Text>
    <Text
      family="heading"
      size="sm"
      class="mono"
    >
      MonoBIG_sm
    </Text>
    <Text
      family="heading"
      size="md"
      class="mono"
    >
      MonoBIG_md
    </Text>
    <Text
      family="heading"
      size="lg"
      class="mono"
    >
      MonoBIG_lg
    </Text>
    <Text
      family="heading"
      size="xl"
      class="mono"
    >
      MonoBIG_xl
    </Text>
  </Flex>
</Flex>
</template>
